### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by cedric-gormond** [cedric-gormond/topologyGUI#7]
- [x] Comment the project !
- [ ] Add open file dialog (PC/Mac ?)
- [x] Find vulnerabilities (memory leak, wrong process,...)
- [ ] Check with IPs ?
